# Generated by Django 4.2.12 on 2026-05-18 12:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_payment_method_order_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('franchise_type', models.CharField(choices=[('franchise', 'Franchise'), ('partner', 'Partner Store'), ('flagship', 'Flagship')], default='franchise', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Platform commission percentage retained from merchant sales.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(max_length=12)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchants/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='merchants/banners/')),
                ('store_policy', models.TextField(blank=True)),
                ('about_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_merchant', to=settings.AUTH_USER_MODEL)),
                ('regional_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_merchants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('merchant_limit', models.PositiveIntegerField(default=0, help_text='0 = unlimited merchants in this territory.')),
                ('is_exclusive', models.BooleanField(default=False, help_text='If True, only one active merchant allowed (when limit=1).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'territories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'slug'], name='merchants_t_is_acti_f8fd56_idx')],
            },
        ),
        migrations.CreateModel(
            name='MerchantWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('withdrawable_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='merchants.merchant')),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='merchants.territory'),
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='merchants.merchant')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'status'], name='merchants_p_merchan_fd5867_idx')],
            },
        ),
        migrations.CreateModel(
            name='MerchantTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale_credit', 'Sale Credit'), ('commission_debit', 'Platform Commission'), ('payout', 'Payout'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='merchants.merchant')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_transactions', to='orders.orderitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', '-created_at'], name='merchants_m_merchan_9f634f_idx'), models.Index(fields=['status', 'transaction_type'], name='merchants_m_status_7b1884_idx')],
            },
        ),
        migrations.CreateModel(
            name='MerchantStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('product_manager', 'Product Manager'), ('inventory_manager', 'Inventory Manager'), ('order_manager', 'Order Manager'), ('support', 'Support Staff')], max_length=30)),
                ('can_manage_products', models.BooleanField(default=False)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('can_manage_orders', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('can_manage_coupons', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='merchants.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'is_active'], name='merchants_m_merchan_b3d705_idx')],
                'unique_together': {('merchant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MerchantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('product_approval', 'Product Approval'), ('product_rejection', 'Product Rejection'), ('new_order', 'New Order'), ('payout_update', 'Payout Update'), ('low_inventory', 'Low Inventory'), ('verification', 'Merchant Verification'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('metadata', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='merchants.merchant')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='merchants_m_recipie_a65a19_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['status', 'verification_status'], name='merchants_m_status_f951c9_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['slug'], name='merchants_m_slug_edd591_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['merchant_id'], name='merchants_m_merchan_f47237_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['territory', 'status'], name='merchants_m_territo_005045_idx'),
        ),
    ]
