# Generated by Django 4.2.12 on 2026-05-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'New Order'), ('user', 'New User'), ('product', 'Product Update'), ('product_approval', 'Product Approval'), ('merchant', 'Merchant Update'), ('payout', 'Payout Update'), ('inventory', 'Low Inventory'), ('system', 'System Alert')], default='order', max_length=20),
        ),
    ]
