# Generated by Django 4.2.12 on 2026-05-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_territories',
            field=models.ManyToManyField(blank=True, related_name='regional_managers', to='merchants.territory'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('regional_manager', 'Regional Manager'), ('merchant', 'Merchant'), ('merchant_staff', 'Merchant Staff'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20),
        ),
    ]
