# Generated by Django 4.2.12 on 2026-05-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_admin_notes_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
    ]
