# Generated by Django 4.2.12 on 2026-05-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('orders', '0004_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_type',
            field=models.CharField(choices=[('hq', 'HQ Fulfillment'), ('merchant', 'Merchant Fulfillment')], default='hq', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('paid_out', 'Paid Out'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['merchant', 'fulfillment_status'], name='orders_orde_merchan_c35e34_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'merchant'], name='orders_orde_order_i_fe81d0_idx'),
        ),
    ]
