# Generated by Cascade on 2026-05-04

from django.db import migrations
from django.utils.text import slugify


def seed_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')

    predefined = [
        'Shoes',
        'T-Shirt',
        'Jeans',
        'Pants',
        'Belt',
        'Purse',
        'Cap',
    ]

    for name in predefined:
        slug = slugify(name)
        # Category currently requires `gender`; set to Unisex by default.
        Category.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'gender': 'U',
            },
        )


def unseed_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    for slug in [
        'shoes',
        't-shirt',
        'jeans',
        'pants',
        'belt',
        'purse',
        'cap',
    ]:
        Category.objects.filter(slug=slug).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_equila_style_product_management'),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
