# Generated by Cascade on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_seed_equila_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='target_group',
            field=models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids'), ('UNISEX', 'Unisex')], default='MEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('KIDS_BOY', 'Kids Boy'), ('KIDS_GIRL', 'Kids Girl'), ('UNISEX', 'Unisex')], default='MALE', max_length=10),
        ),
    ]
